### PR TITLE
Add logos

### PR DESCRIPTION
**Pull request by martynchamberlin**
This adds 90 new logos to Secrets. I've also changed the wildcards on a few preexisting ones to be more lenient. Looking forward to hearing what you think!

### CODE REVIEW

**Comment by pfandrade** [comment]
This is awesome! Thanks!

**Comment by martynchamberlin** [comment]
Yay! Any ideas when the next release of the app will be?

**Comment by pfandrade** [comment]
This doesn't require a new release, the app will check for updated logos once a week. You should be able to delete the Logos folder here:

~/Library/Containers/com.outercorner.osx.Secrets/Data/Library/Application\ Support/Outer\ Corner/Secrets/Logos

To force an update (requires an app restart).

**Comment by martynchamberlin** [comment]
Cool! 

Though you do have to do something on your end other than merge this, right? For example I'm noticing 3 sizes of the logos for every image in that directory.

**Comment by pfandrade** [comment]
Yes I do. I have a script that runs through the service map (and credit card map) and generates all the logos at the correct sizes.

I might stop sending the 3 versions in the future and let the client handle that (I would just send the larger version).

**Pull request merged**
